//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MidAssignment_ZeroHunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collect_Request
    {
        public int CollectReqId { get; set; }
        public int RestaurantsId { get; set; }
        public string Food_Name { get; set; }
        public string Food_Description { get; set; }
        public int Food_Quantity { get; set; }
        public int Preservation_Time { get; set; }
        public System.DateTime Request_Time { get; set; }
        public string Employee_Status { get; set; }
        public Nullable<int> Employee_id { get; set; }
        public string Distribution_Status { get; set; }
        public int NgoId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual NGO NGO { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
